<?php

namespace Database\Seeders;

use App\Models\Perusahaan;
use Illuminate\Database\Seeder;

class PerusahaanMitraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $companies = [
            [
                'nama_perusahaan' => 'PT. BESRA UTAMA SINARAN',
                'alamat' => 'Jl. H. Imam Munandar / Harapan Raya No. 381, Tangkerang Timur, Kec. Tenayan Raya',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0811-7521-118',
                'email' => 'info@besra.co.id',
                'website' => 'https://besra.co.id',
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. BANK RIAU KEPRI SYARIAH PEKANBARU MARPOYAN',
                'alamat' => 'Jl. Kaharuddin Nasution No. 12, Simpang Tiga, Kec. Marpoyan Damai',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-674848',
                'email' => 'corsec@brksyariah.co.id',
                'website' => 'https://www.brksyariah.co.id',
                'nama_pimpinan' => 'Pemimpin Cabang',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'MULTI COMPUTER',
                'alamat' => 'Jl. Tuanku Tambusai / Nangka No. 138',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-28562',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'UNIVERSITAS HANG TUAH PEKANBARU',
                'alamat' => 'Jl. Mustafa Sari No. 5, Tangkerang Selatan, Kec. Bukit Raya',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-33815',
                'email' => 'info@uhtp.ac.id',
                'website' => 'https://uhtp.ac.id',
                'nama_pimpinan' => 'Rektor',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. UPAYA TEHNIK',
                'alamat' => 'Jl. SM Amin No. 18, Simpang Baru, Kec. Tampan / Bina Widya',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-564567',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PROMEDIA KOMPUTER',
                'alamat' => 'Jl. Tuanku Tambusai / Nangka No. 343 C-D',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0852-7104-5222',
                'email' => 'sales@promediakomputer.com',
                'website' => 'https://promediakomputer.com',
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PERPUSTAKAAN FKIP UNIVERSITAS RIAU',
                'alamat' => 'Kampus Bina Widya Km. 12,5, Simpang Baru, Kec. Bina Widya',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-63266',
                'email' => 'fkip@lecturer.unri.ac.id',
                'website' => 'https://fkip.unri.ac.id',
                'nama_pimpinan' => 'Kepala Perpustakaan',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'RUMAH SAKIT IBU DAN ANAK ZAINAB',
                'alamat' => 'Jl. Ronggowarsito I No. 1, Suka Maju, Kec. Sail',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-24000',
                'email' => 'rsiazainab@yahoo.com',
                'website' => 'https://rsiazainab.co.id',
                'nama_pimpinan' => 'Direktur RSIA Zainab',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'CV. RETYAN COMPUTER',
                'alamat' => 'Jl. Melati No. 42 / Jl. HR Soebrantas',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0812-7567-891',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'ICT CENTER PEKANBARU',
                'alamat' => 'Kompleks SMKN 2 Pekanbaru, Jl. Pattimura No. 20, Sail',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-23136',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => 'Kepala UPT ICT',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. JAMKRIDA RIAU',
                'alamat' => 'Jl. Jend. Sudirman No. 438, Jadirejo, Kec. Sukajadi',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-848808',
                'email' => 'kontak@jamkridariau.co.id',
                'website' => 'https://jamkridariau.co.id',
                'nama_pimpinan' => 'Direktur Utama',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. LINTAS RIAU PRIMA',
                'alamat' => 'Jl. Tuanku Tambusai No. 88, Komp. Pertokoan Nangka Mas',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-572211',
                'email' => 'lintasriauprima@gmail.com',
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. TELKOM WITEL RIDAR',
                'alamat' => 'Jl. Jend. Sudirman No. 199, Sumahilang, Kec. Pekanbaru Kota',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-31000',
                'email' => 'customercare@telkom.co.id',
                'website' => 'https://www.telkom.co.id',
                'nama_pimpinan' => 'General Manager Witel Riau Daratan',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. GLOBALRIAU DATA SOLUSI',
                'alamat' => 'Jl. Cendana No. 1, Komp. Purwodadi Indah, Sidomulyo Barat, Tampan',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-7777554',
                'email' => 'online@gds.net.id',
                'website' => 'https://gds.net.id',
                'nama_pimpinan' => 'Direktur',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. ADITAMA NETMEDIA SOLUSINDO',
                'alamat' => 'Jl. Cendana No. 1, Komp. Purwodadi Indah, Sidomulyo Barat, Tampan',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0811-7671-099',
                'email' => 'admin@aditama.net',
                'website' => 'https://aditama.net.id',
                'nama_pimpinan' => 'Direktur',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'DINAS KEPEMUDAAN DAN OLAHRAGA PROVINSI RIAU',
                'alamat' => 'Jl. Sutomo No. 114, Rintis, Kec. Lima Puluh',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-22443',
                'email' => 'dispora@riau.go.id',
                'website' => 'https://dispora.riau.go.id',
                'nama_pimpinan' => 'Kepala Dinas',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. HSN TECH INDONESIA',
                'alamat' => 'Jl. Air Dingin No. 28, Simpang Tiga, Kec. Bukit Raya',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0812-7001-234',
                'email' => 'info@hsntech.co.id',
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. POS INDONESIA (Persero)',
                'alamat' => 'Jl. Jend. Sudirman No. 229, Pekanbaru Kota',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-21503',
                'email' => 'halopos@posindonesia.co.id',
                'website' => 'https://www.posindonesia.co.id',
                'nama_pimpinan' => 'Executive GM KCU Pekanbaru',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'FAKULTAS KEPERAWATAN UNIVERSITAS RIAU',
                'alamat' => 'Jl. Pattimura No. 9, Gedung E, Cinta Raja, Sail',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-37884',
                'email' => 'fkp@unri.ac.id',
                'website' => 'https://fkp.unri.ac.id',
                'nama_pimpinan' => 'Dekan',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. MEDIA ANDALAN NUSA',
                'alamat' => 'Gedung Cyber 2 Lt. 18 / Branch Pekanbaru',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '021-29964900',
                'email' => 'info@andalan.net.id',
                'website' => 'https://andalan.net.id',
                'nama_pimpinan' => 'Branch Manager',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'TEKUN JAYA SECURINDO',
                'alamat' => 'Jl. Tuanku Tambusai No. 289 B, Wonorejo, Kec. Marpoyan Damai',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-39699',
                'email' => 'tekunjayasecurindo@gmail.com',
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. HEMATECH NUSANTARA',
                'alamat' => 'Jl. Durian No. 43, Labuh Baru Timur, Kec. Sukajadi',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-43899',
                'email' => 'info@hematech.co.id',
                'website' => 'https://www.hematech.co.id',
                'nama_pimpinan' => 'Direktur',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'UPT TIK (PUSKOM) UNIVERSITAS RIAU',
                'alamat' => 'Kampus Bina Widya Km. 12,5, Gedung Puskom, Panam',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-63275',
                'email' => 'upttik@unri.ac.id',
                'website' => 'https://upttik.unri.ac.id',
                'nama_pimpinan' => 'Kepala UPT TIK',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'LEGEND COMPUTER',
                'alamat' => 'Jl. HR. Soebrantas No. 88 Panam, Kec. Tampan / Bina Widya',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0852-6548-1234',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'RUMAH SAKIT Prof. Dr. TABRANI',
                'alamat' => 'Jl. Jend. Sudirman No. 410, Wonorejo, Kec. Marpoyan Damai',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-35464',
                'email' => 'rstabrani@gmail.com',
                'website' => 'https://rstabrani.co.id',
                'nama_pimpinan' => 'Direktur Rumah Sakit',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. PERMODALAN EKONOMI RAKYAT',
                'alamat' => 'Jl. Jend. Sudirman No. 468, Jadirejo, Kec. Sukajadi',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-855734',
                'email' => 'sekretariat@per.co.id',
                'website' => 'https://per.co.id',
                'nama_pimpinan' => 'Direktur Utama',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'BESS COMPUTER',
                'alamat' => 'Jl. Tuanku Tambusai / Nangka No. 128',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-38290',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'SOLUSI DATA MADANI',
                'alamat' => 'Jl. Garuda Sakti Km. 1, Simpang Baru, Tampan',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0812-7654-3210',
                'email' => 'info@solusidatamadani.com',
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. ASIA FORESTAMA RAYA',
                'alamat' => 'Jl. Teluk Leok No. 1, Limbungan, Kec. Rumbai Timur',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-51016',
                'email' => 'corsec@asiaforestama.com',
                'website' => null,
                'nama_pimpinan' => 'Direktur',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'ASSIST.ID',
                'alamat' => 'Jl. Kyai Maja No. 25-27, Kebayoran Baru, Jakarta Selatan (Layanan Nasional / Pekanbaru)',
                'kota' => 'Jakarta / Pekanbaru',
                'no_telepon' => '0813-8222-7747',
                'email' => 'halo@assist.id',
                'website' => 'https://assist.id',
                'nama_pimpinan' => 'CEO',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. ANUGRAH ANALISIS SEMPURNA',
                'alamat' => 'Jl. SM Amin Komp. Pergudangan / Perwakilan Lab Lingkungan Pekanbaru',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-8419200',
                'email' => 'marketing@aaslaboratory.com',
                'website' => 'https://aaslaboratory.com',
                'nama_pimpinan' => 'Kepala Cabang',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. NETVIRO',
                'alamat' => 'Jl. Delima No. 12, Tobek Godang, Tampan',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0811-7575-889',
                'email' => 'info@netviro.com',
                'website' => 'https://netviro.com',
                'nama_pimpinan' => 'Direktur',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. SOLUSI UMMAT APLIKASI INDONESIA',
                'alamat' => 'Jl. Melati Indah, Delima, Kec. Tampan / Bina Widya',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0812-6800-4545',
                'email' => 'support@solusiummat.com',
                'website' => null,
                'nama_pimpinan' => 'Direktur',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'AKADEMI MANAJEMEN INFORMATIKA DAN KOMPUTER MAHAPUTERA RIAU',
                'alamat' => 'Jl. Soebrantas No. 77 Km. 11 Panam, Simpang Baru, Tampan',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-588145',
                'email' => 'amikmahaputerariau@gmail.com',
                'website' => 'https://amikmahaputera.ac.id',
                'nama_pimpinan' => 'Direktur AMIK Mahaputera',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. TELKOM RIAU DARATAN',
                'alamat' => 'Jl. Jend. Sudirman No. 199, Pekanbaru',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-31000',
                'email' => 'customercare@telkom.co.id',
                'website' => 'https://www.telkom.co.id',
                'nama_pimpinan' => 'General Manager',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'UTAMA COMPUTER',
                'alamat' => 'Jl. Tuanku Tambusai No. 248, Labuh Baru Timur, Payung Sekaki',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-26788',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. INDONESIA COMNETS PLUS',
                'alamat' => 'Jl. Setia Maharaja / Parit Indah No. 10, Tangkerang Labuai, Bukit Raya',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-8408080',
                'email' => 'kontak@plniconplus.co.id',
                'website' => 'https://plniconplus.co.id',
                'nama_pimpinan' => 'General Manager SBU Sumbagteng',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'YAYASAN DINIYYAH PEKANBARU',
                'alamat' => 'Jl. KH. Ahmad Dahlan No. 100, Sukajadi',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-23749',
                'email' => 'yayasan@diniyyahpekanbaru.org',
                'website' => 'https://diniyyahpekanbaru.org',
                'nama_pimpinan' => 'Ketua Yayasan',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. GARUDA CYBER INDONESIA',
                'alamat' => 'Jl. HR. Soebrantas No. 188, Sidomulyo Barat, Kec. Tampan',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0811-7674-727',
                'email' => 'garudacyberindo@gmail.com',
                'website' => 'https://garudacyber.co.id',
                'nama_pimpinan' => 'Direktur Utama',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL KOTA PEKANBARU',
                'alamat' => 'Komp. Mal Pelayanan Publik (MPP), Jl. Jend. Sudirman No. 464, Jadirejo',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-46011',
                'email' => 'disdukcapil@pekanbaru.go.id',
                'website' => 'https://disdukcapil.pekanbaru.go.id',
                'nama_pimpinan' => 'Kepala Dinas',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'KANTOR LAYANAN TEKNIS (KLT)',
                'alamat' => 'KLT BSN Riau, Gedung Riau Creative Hub, Jl. Arifin Achmad',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-8415250',
                'email' => 'kltriau@bsn.go.id',
                'website' => 'https://bsn.go.id',
                'nama_pimpinan' => 'Kepala Kantor Layanan Teknis',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'KEJAKSAAN TINGGI RIAU',
                'alamat' => 'Jl. Jend. Sudirman No. 375, Simpang Empat, Pekanbaru Kota',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-31215',
                'email' => 'kejati_riau@kejaksaan.go.id',
                'website' => 'https://kejati-riau.kejaksaan.go.id',
                'nama_pimpinan' => 'Kepala Kejaksaan Tinggi Riau',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. KEMANG FOOD INDUSTRI',
                'alamat' => 'Perwakilan Distribusi Pekanbaru, Jl. Arengka II / SM Amin',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '021-8710375',
                'email' => 'info@kemfood.co.id',
                'website' => 'https://kemfood.co.id',
                'nama_pimpinan' => 'Kepala Cabang / Depot',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'FRANSILVIA CONSULTING',
                'alamat' => 'Jl. Melur No. 24, Sukajadi',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0812-7601-998',
                'email' => 'info@fransilviaconsulting.com',
                'website' => null,
                'nama_pimpinan' => 'Pimpinan Konsultan',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. PUTRA SINAR UTAMA',
                'alamat' => 'Jl. Riau No. 147, Kampung Baru, Kec. Senapelan',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-857390',
                'email' => 'putrasinarutama@gmail.com',
                'website' => null,
                'nama_pimpinan' => 'Direktur',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'BANK RIAU KEPRI SYARIAH CAPEM SENAPELAN',
                'alamat' => 'Jl. Senapelan No. 64, Kampung Bandar, Kec. Senapelan',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-22874',
                'email' => 'corsec@brksyariah.co.id',
                'website' => 'https://www.brksyariah.co.id',
                'nama_pimpinan' => 'Pemimpin Capem',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'CV. BINTANG TERANG',
                'alamat' => 'Jl. Tuanku Tambusai No. 102, Payung Sekaki',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-33120',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'EKA HOSPITAL PEKANBARU',
                'alamat' => 'Jl. Soekarno-Hatta Km. 6.5, Tengkerang Barat, Kec. Marpoyan Damai',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-6989999',
                'email' => 'customercare-pku@ekahospital.com',
                'website' => 'https://ekahospital.com',
                'nama_pimpinan' => 'Direktur Rumah Sakit',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'ASIA GROUP',
                'alamat' => 'Jl. Jend. Sudirman No. 320 / Kawasan Industri Tenayan',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-36888',
                'email' => 'info@asiagroup.co.id',
                'website' => null,
                'nama_pimpinan' => 'Direksi',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'CV. MITRA SOLUTION TAXINDO',
                'alamat' => 'Jl. Belimbing No. 15, Wonorejo, Kec. Marpoyan Damai',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0812-7589-9800',
                'email' => 'taxindo@mitrasolution.com',
                'website' => null,
                'nama_pimpinan' => 'Pimpinan Konsultan',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. PEPUTRA MASTERINDO',
                'alamat' => 'Jl. Jend. Sudirman No. 395, Wonorejo, Marpoyan Damai',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-34444',
                'email' => 'masterindo@peputra.co.id',
                'website' => null,
                'nama_pimpinan' => 'Direktur Utama',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'TOKO ASIA ELEKTRIKAL CENTER',
                'alamat' => 'Jl. Tuanku Tambusai / Nangka No. 89 A-B',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-27715',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. AGUNG AUTOMALL',
                'alamat' => 'Jl. Dr. Sutomo No. 13, Sekip, Kec. Lima Puluh',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-24888',
                'email' => 'customer@agungtoyota.co.id',
                'website' => 'https://agungtoyota.co.id',
                'nama_pimpinan' => 'Branch Manager',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'CV. PUTRA JAYA PERKASA',
                'alamat' => 'Jl. Harapan Raya / H. Imam Munandar No. 152',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0813-7188-9922',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. PEPUTRA SUPRA JAYA',
                'alamat' => 'Jl. Jend. Sudirman No. 395, Gedung Peputra Group',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-34444',
                'email' => 'suprajaya@peputra.co.id',
                'website' => null,
                'nama_pimpinan' => 'Direktur Utama',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. BANK NEGARA INDONESIA (Persero) Tbk',
                'alamat' => 'Jl. Jend. Sudirman No. 119, KCU Pekanbaru, Kota Tinggi',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-22684',
                'email' => 'bnicall@bni.co.id',
                'website' => 'https://www.bni.co.id',
                'nama_pimpinan' => 'Pemimpin Cabang KCU Pekanbaru',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. PERKEBUNAN NUSANTARA V',
                'alamat' => 'Jl. Rambutan No. 43, Sidomulyo Timur, Kec. Marpoyan Damai',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-66565',
                'email' => 'sekretariat@ptpn5.co.id',
                'website' => 'https://ptpn5.co.id',
                'nama_pimpinan' => 'Region Head (PTPN IV Regional III)',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'DINAS PERPUSTAKAAN DAN KEARSIPAN PROVINSI RIAU',
                'alamat' => 'Jl. Jend. Sudirman No. 462 (Gedung Perpustakaan Soeman HS), Jadirejo',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-34068',
                'email' => 'dipersip@riau.go.id',
                'website' => 'https://dipersip.riau.go.id',
                'nama_pimpinan' => 'Kepala Dinas',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'FOX HOTEL PEKANBARU',
                'alamat' => 'Jl. Riau No. 147, Padang Terubuk, Kec. Senapelan',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-7415999',
                'email' => 'info-fox-pekanbaru@tauzia.com',
                'website' => 'https://www.discoverasr.com',
                'nama_pimpinan' => 'General Manager',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'BADAN PENDAPATAN DAERAH PROVINSI RIAU',
                'alamat' => 'Jl. Jend. Sudirman No. 458, Kompleks Perkantoran Pemprov Riau',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-34127',
                'email' => 'bapenda@riau.go.id',
                'website' => 'https://bapenda.riau.go.id',
                'nama_pimpinan' => 'Kepala Bapenda Riau',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'DINAS PERINDUSTRIAN, PERDAGANGAN, KOPERASI USAHA KECIL DAN MENENGAH PROVINSI RIAU',
                'alamat' => 'Jl. Cut Nyak Dien No. 3, Jadirejo, Sukajadi',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-21820',
                'email' => 'disperindagkopukm@riau.go.id',
                'website' => 'https://disperindagkopukm.riau.go.id',
                'nama_pimpinan' => 'Kepala Dinas',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'KANTOR REGIONAL XII BKN PEKANBARU',
                'alamat' => 'Jl. Hang Tuah Ujung No. 148, Rejosari, Kec. Tenayan Raya',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-73693',
                'email' => 'kanreg12.pekanbaru@bkn.go.id',
                'website' => 'https://kanreg12bkn.id',
                'nama_pimpinan' => 'Kepala Kantor Regional XII',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'SEKRETARIAT DAERAH PROVINSI RIAU',
                'alamat' => 'Gedung Menara Lancang Kuning, Jl. Jend. Sudirman No. 460',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-31401',
                'email' => 'humas@riau.go.id',
                'website' => 'https://riau.go.id',
                'nama_pimpinan' => 'Sekretaris Daerah Provinsi Riau',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. AGRO ABADI',
                'alamat' => 'Jl. KH. Ahmad Dahlan No. 45, Kampung Melayu, Sukajadi',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-28945',
                'email' => 'info@agroabadi.co.id',
                'website' => null,
                'nama_pimpinan' => 'Direktur',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PT. SUCOFINDO',
                'alamat' => 'Jl. Jend. Ahmad Yani No. 79, Sukajadi',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-35688',
                'email' => 'pekanbaru@sucofindo.co.id',
                'website' => 'https://www.sucofindo.co.id',
                'nama_pimpinan' => 'Kepala Cabang Pekanbaru',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'KANTOR PELAYANAN PERBENDAHARAAN NEGARA',
                'alamat' => 'KPPN Pekanbaru, Jl. Jend. Sudirman No. 247, Sail',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-23112',
                'email' => 'kppnpekanbaru@kemenkeu.go.id',
                'website' => 'https://djpb.kemenkeu.go.id/kppn/pekanbaru',
                'nama_pimpinan' => 'Kepala KPPN Pekanbaru',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'PERPUSTAKAAN CABANG FKIP UNIVERSITAS RIAU',
                'alamat' => 'Kampus Bina Widya Km. 12,5, FKIP Gedung D, Panam',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-63266',
                'email' => 'fkip@lecturer.unri.ac.id',
                'website' => 'https://fkip.unri.ac.id',
                'nama_pimpinan' => 'Kepala Perpustakaan Cabang',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU',
                'alamat' => 'DPMPTSP Provinsi Riau, Gedung Menara Lancang Kuning Lt. 1-2, Jl. Sudirman',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-39132',
                'email' => 'dpmptsp@riau.go.id',
                'website' => 'https://dpmptsp.riau.go.id',
                'nama_pimpinan' => 'Kepala Dinas DPMPTSP',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'BIRO ADMINISTRASI PEMBANGUNAN',
                'alamat' => 'Kantor Gubernur Riau, Jl. Jend. Sudirman No. 460',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-31401',
                'email' => 'birobang@riau.go.id',
                'website' => 'https://adbang.riau.go.id',
                'nama_pimpinan' => 'Kepala Biro Administrasi Pembangunan',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'CV. INDAH KARYA ABADI',
                'alamat' => 'Jl. Taskurun No. 48, Wonorejo, Marpoyan Damai',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0812-7633-211',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'BANK RIAU KEPRI SYARIAH PEKANBARU',
                'alamat' => 'Menara Dang Merdu BRK Syariah, Jl. Jend. Sudirman No. 462',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-47070',
                'email' => 'corsec@brksyariah.co.id',
                'website' => 'https://www.brksyariah.co.id',
                'nama_pimpinan' => 'Pemimpin Cabang Utama',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'DINAS SOSIAL PROVINSI RIAU',
                'alamat' => 'Jl. Jend. Sudirman No. 504, Tangkerang Selatan, Bukit Raya',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-32543',
                'email' => 'dinsos@riau.go.id',
                'website' => 'https://dinsos.riau.go.id',
                'nama_pimpinan' => 'Kepala Dinas Sosial',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'KANTOR WILAYAH BADAN PERTANAHAN NASIONAL',
                'alamat' => 'Kanwil BPN Provinsi Riau, Jl. Cut Nyak Dien No. 2, Jadirejo, Sukajadi',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-22441',
                'email' => 'riau@atrbpn.go.id',
                'website' => 'https://riau.atrbpn.go.id',
                'nama_pimpinan' => 'Kepala Kantor Wilayah ATR/BPN',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'BIRO ADMINISTRASI PIMPINAN',
                'alamat' => 'Sekretariat Daerah Kantor Gubernur Riau, Menara Lancang Kuning Lt. 7',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-31401',
                'email' => 'adpim@riau.go.id',
                'website' => 'https://adpim.riau.go.id',
                'nama_pimpinan' => 'Kepala Biro Adpim Setda Prov Riau',
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => 'SWALAYAN MAMMA MIA',
                'alamat' => 'Jl. Belimbing No. 34 / Jl. Paus No. 12, Wonorejo, Marpoyan Damai',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0761-38910',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
            [
                'nama_perusahaan' => '999 KIOSK SWALAYAN',
                'alamat' => 'Jl. HR. Soebrantas No. 25 Panam, Simpang Baru, Tampan',
                'kota' => 'Kota Pekanbaru',
                'no_telepon' => '0812-6899-999',
                'email' => null,
                'website' => null,
                'nama_pimpinan' => null,
                'status' => 'aktif',
            ],
        ];

        foreach ($companies as $company) {
            Perusahaan::updateOrCreate(
                ['nama_perusahaan' => $company['nama_perusahaan']],
                $company
            );
        }
    }
}
