@csrf
<div class="row g-3">
    <div class="col-md-4"><label class="form-label">NIS <span class="text-danger">*</span></label><input name="nis" value="{{ old('nis',$siswa->nis ?? '') }}" class="form-control" required></div>
    <div class="col-md-4"><label class="form-label">NISN</label><input name="nisn" value="{{ old('nisn',$siswa->nisn ?? '') }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Jenis Kelamin</label><select name="jenis_kelamin" class="form-select"><option value="">- Pilih -</option><option value="L" @selected(old('jenis_kelamin',$siswa->jenis_kelamin ?? '')==='L')>Laki-laki</option><option value="P" @selected(old('jenis_kelamin',$siswa->jenis_kelamin ?? '')==='P')>Perempuan</option></select></div>
    <div class="col-md-8"><label class="form-label">Nama Siswa <span class="text-danger">*</span></label><input name="nama" value="{{ old('nama',$siswa->nama ?? '') }}" class="form-control" required></div>
    <div class="col-md-4"><label class="form-label">No. HP</label><input name="no_hp" value="{{ old('no_hp',$siswa->no_hp ?? '') }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Jurusan <span class="text-danger">*</span></label><select name="jurusan_id" class="form-select" required><option value="">- Pilih Jurusan -</option>@foreach($jurusan as $item)<option value="{{ $item->id }}" @selected(old('jurusan_id',$siswa->jurusan_id ?? '')==$item->id)>{{ $item->kode_jurusan }} - {{ $item->nama_jurusan }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Kelas <span class="text-danger">*</span></label><select name="kelas_id" class="form-select" required><option value="">- Pilih Kelas -</option>@foreach($kelas as $item)<option value="{{ $item->id }}" @selected(old('kelas_id',$siswa->kelas_id ?? '')==$item->id)>{{ $item->nama_kelas }} ({{ $item->jurusan?->kode_jurusan }})</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Status Akun</label><select name="status" class="form-select"><option value="aktif" @selected(old('status',$siswa->user?->status ?? 'aktif')==='aktif')>Aktif</option><option value="nonaktif" @selected(old('status',$siswa->user?->status ?? '')==='nonaktif')>Nonaktif</option></select></div>
    <div class="col-md-4"><label class="form-label">Tempat Lahir</label><input name="tempat_lahir" value="{{ old('tempat_lahir',$siswa->tempat_lahir ?? '') }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Tanggal Lahir</label><input type="date" name="tanggal_lahir" value="{{ old('tanggal_lahir', optional($siswa->tanggal_lahir ?? null)->format('Y-m-d')) }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Email Login <span class="text-danger">*</span></label><input type="email" name="email" value="{{ old('email',$siswa->user?->email ?? '') }}" class="form-control" required></div>
    <div class="col-12"><label class="form-label">Alamat</label><textarea name="alamat" rows="3" class="form-control">{{ old('alamat',$siswa->alamat ?? '') }}</textarea></div>
    <div class="col-md-6"><label class="form-label">Password {{ isset($siswa) ? '(kosongkan jika tidak diubah)' : '' }} <span class="text-danger">{{ isset($siswa) ? '' : '*' }}</span></label><input type="password" name="password" class="form-control" {{ isset($siswa) ? '' : 'required' }} minlength="8"></div>
</div>
