@csrf
<div class="row g-3">
    <div class="col-md-8"><label class="form-label">Nama Guru <span class="text-danger">*</span></label><input name="nama" value="{{ old('nama',$guru->nama ?? '') }}" class="form-control @error('nama') is-invalid @enderror" required>@error('nama')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">NIP</label><input name="nip" value="{{ old('nip',$guru->nip ?? '') }}" class="form-control">@error('nip')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">Jenis Kelamin</label><select name="jenis_kelamin" class="form-select"><option value="">- Pilih -</option><option value="L" @selected(old('jenis_kelamin',$guru->jenis_kelamin ?? '')==='L')>Laki-laki</option><option value="P" @selected(old('jenis_kelamin',$guru->jenis_kelamin ?? '')==='P')>Perempuan</option></select></div>
    <div class="col-md-4"><label class="form-label">No. HP</label><input name="no_hp" value="{{ old('no_hp',$guru->no_hp ?? '') }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Status Akun</label><select name="status" class="form-select"><option value="aktif" @selected(old('status',$guru->user?->status ?? 'aktif')==='aktif')>Aktif</option><option value="nonaktif" @selected(old('status',$guru->user?->status ?? '')==='nonaktif')>Nonaktif</option></select></div>
    <div class="col-12"><label class="form-label">Alamat</label><textarea name="alamat" rows="3" class="form-control">{{ old('alamat',$guru->alamat ?? '') }}</textarea></div>
    <div class="col-md-6"><label class="form-label">Email Login <span class="text-danger">*</span></label><input type="email" name="email" value="{{ old('email',$guru->user?->email ?? '') }}" class="form-control @error('email') is-invalid @enderror" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Password {{ isset($guru) ? '(kosongkan jika tidak diubah)' : '(default: guru1234)' }}</label><input type="text" name="password" class="form-control" placeholder="Default: guru1234" minlength="6">@error('password')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror<div class="form-text text-muted" style="font-size: 0.775rem;">Jika dikosongkan, password otomatis diset ke <strong>guru1234</strong>.</div></div>
</div>
